services:
  webapp:
    image: label-studio:1.13.1.20250729.1.fjs
    container_name: label_studio
    depends_on:
      - lb_backend
    restart: always
    environment:
      # - LABEL_STUDIO_HOST=https://aiservice.fujinet.net/lb
      - COLLECT_ANALYTICS=False
      - collect_analytics=0
      - LOCAL_FILES_SERVING_ENABLED=True # Must be set to True to use local files
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files # Must be set to /label-studio/files to use local files
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_USERNAME=example@email.com
      - LABEL_STUDIO_PASSWORD=Abc12345
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=postgres
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=lb_backend
      - fflag_feat_front_lsdv_4583_multi_image_segmentation_short=1
    ports:
      - "8080:8080"
    volumes:
      - .data/label_studio_data:/label-studio/data # App data
      - .data/imagedata/AI01:/label-studio/files/AI01 # Mount image data
  lb_backend:
    image: postgres:14
    container_name: ls-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labelstudio
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres_data:/var/lib/postgresql/data
